# Generated by Django 3.1.4 on 2021-01-01 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_website_only_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status_job', models.CharField(blank=True, max_length=30, null=True)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='org.website')),
            ],
        ),
    ]
