# Generated by Django 3.0.6 on 2020-12-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0006_auto_20201213_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor',
            name='type_audit',
            field=models.CharField(blank=True, choices=[('HEADERS', 'Headers'), ('IMAGES', 'Images')], max_length=20),
        ),
    ]
