# Generated by Django 3.0.6 on 2020-12-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('result', models.TextField()),
                ('type_audit', models.CharField(max_length=30)),
                ('task_id', models.CharField(max_length=30)),
                ('status_job', models.CharField(max_length=30)),
                ('begin_date', models.DateTimeField()),
            ],
        ),
    ]
