# Generated by Django 3.0.6 on 2020-12-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor',
            name='begin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractor',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractor',
            name='status_job',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='extractor',
            name='task_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
