# Generated by Django 3.0.6 on 2020-12-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_auto_20201213_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor',
            name='type_audit',
            field=models.CharField(blank=True, choices=[('HEADER', 'Header')], max_length=20),
        ),
    ]
