# Generated by Django 3.1.4 on 2020-12-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_website_only_domain'),
        ('extractor', '0012_auto_20201222_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('result', models.JSONField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status_job', models.CharField(blank=True, max_length=30, null=True)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap', to='org.website')),
            ],
        ),
    ]
