# Generated by Django 3.1.4 on 2020-12-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('div', models.TextField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('maximum', models.IntegerField()),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status_job', models.CharField(blank=True, max_length=30, null=True)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
