# Generated by Django 3.1.4 on 2020-12-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_auto_20201216_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
