# Generated by Django 3.1.4 on 2020-12-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_auto_20201217_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('YAKE', 'Yake')], max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('ngram', models.IntegerField(max_length=20)),
                ('language', models.CharField(max_length=10)),
                ('number_keywords', models.IntegerField(max_length=200)),
                ('status_job', models.CharField(blank=True, max_length=20, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
