# Generated by Django 3.1.4 on 2020-12-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0004_auto_20201227_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yake',
            name='method',
        ),
    ]
