# Generated by Django 3.1.4 on 2020-12-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0005_remove_yake_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yake',
            name='ngram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yake',
            name='number_keywords',
            field=models.IntegerField(),
        ),
    ]
