# Generated by Django 3.1.4 on 2021-01-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_website_only_domain'),
        ('keywords', '0007_yake_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='yake',
            name='org',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, related_name='yake', to='org.website'),
            preserve_default=False,
        ),
    ]
