# Generated by Django 3.1.4 on 2021-01-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_website_only_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('scheduled', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security', to='org.website')),
            ],
        ),
        migrations.CreateModel(
            name='Security_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwa_score', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_results_org', to='org.website')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_results', to='security.security')),
            ],
        ),
    ]
