# Generated by Django 3.0.6 on 2020-12-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0002_auto_20201215_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighthouse',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
