# Generated by Django 3.0.6 on 2020-12-15 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0005_auto_20201215_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighthouse_result',
            name='performance_score',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lighthouse_result',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighthouse_results', to='lighthouse.Lighthouse'),
        ),
    ]
