# Generated by Django 3.0.6 on 2020-12-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0006_auto_20201215_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lighthouse_result',
            name='result',
        ),
        migrations.AlterField(
            model_name='lighthouse_result',
            name='performance_score',
            field=models.TextField(max_length=10),
        ),
    ]
