# Generated by Django 3.0.6 on 2020-12-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0008_auto_20201215_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighthouse_result',
            name='accessibility_score',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighthouse_result',
            name='best_practices_score',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighthouse_result',
            name='pwa_score',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighthouse_result',
            name='seo_score',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
